# WhatATheme
markdown: virdesm.github.io

# URL of the Site
url: 'https://virdesm.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: /virginie.desmedt.github.io/

# Title of the Site
title: Portfolio
# Description of the Site
description: Virginie Desmedt
# URL of Image of the Site
site-image: https://raw.githubusercontent.com/virdesm/virginie.desmedt.github.io/gh-pages/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 
logoimage: https://raw.githubusercontent.com/virdesm/virginie.desmedt.github.io/gh-pages/assets/images/logo.png
# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://raw.githubusercontent.com/virdesm/virginie.desmedt.github.io/gh-pages/assets/images/meta.jpg
# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: virgdesmedt@hotmail.com
linkedin_username: www.linkedin.com/in/virginiedesmedt
github_username:  virdesm


# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: Virginie Desmedt

# Name of the Author
author-name: Virginie Desmedt
# URL for the Image of the Author
author-image: https://raw.githubusercontent.com/virdesm/virginie.desmedt.github.io/gh-pages/assets/images/vd.jpg
# 60 Words About the Author
author-about: I create accessible and performant user experiences on the web. I have been provided highly valuable design and achievement for large-scale digital plaforms. 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
